### ISSUE TITLE
Detached head when loading PolyMath from baselines

### ISSUE THREAD

**Issue by jordanmontt** [PolyMathOrg/PolyMath#211]
I am not quite sure if this it's an error but I am reporting just in case :)
When you load the development version of PolyMath using the Metacello script of the README, there are some detached head repos that are loaded:
![Screenshot 2021-07-20 at 16 14 43](https://user-images.githubusercontent.com/33934979/126339847-9a0366e9-dd12-446c-8757-c9fa17b3a8fb.png)

**Comment by capsulecorplab** [comment]
I suspect that's because those are dependencies of PolyMath that are pinned to a specific commit, tagged with a [semver](http://semver.org/)-compliant version. This just means that Git has checked out a specific commit that isn't the `HEAD` commit of a branch for those dependencies, which is what you want for ensuring reproducible behavior in an applications that uses 3rd party libraries

**Comment by SergeStinckwich** [comment]
Thank you for your report Sebastian. As mentioned, this is more a feature than a bug. We want PolyMath to depend to specific versions for external libraries in order to avoid any surprise if dependencies change. We have to check if all dependencies have fixed versions, not sure about that.
