### ISSUE TITLE
PMVector #tensorProduct symmetric case returns same matrix for all products

### ISSUE THREAD

**Issue by apocalypsemystic** [PolyMathOrg/PolyMath#25]
The PMVector #tensorProduct: implementation checks whether the products are #== so that it can return a PMSymmetricMatrix, but the returned matrix does not actually look at the values in the vector; it returns the same PMSymmetricMatrix for all values.

zeros := PMVector zeros: 2.
zeros tensorProduct: (PMVector zeros: 2).
 "a PMVector(0 0)
a PMVector(0 0)"
zeros tensorProduct: zeros.
 "a PMVector(1 2)
a PMVector(2 4)"

ones := PMVector ones: 2.
ones tensorProduct: (PMVector ones: 2).
 "a PMVector(1 1)
a PMVector(1 1)"
ones tensorProduct: ones.
 "a PMVector(1 2)
a PMVector(2 4)"

**Comment by olekscode** [comment]
I have fixed this issue by making a small change in the tensorProduct: message

```
tensorProduct: aVector
    "Answers the tensor product of the receiver with aVector."
    ^self == aVector "dont use #="
        ifTrue: [PMSymmetricMatrix new: self size function:[:x :y| (self at: x) * (self at: y) ]] 
        ifFalse:[PMMatrix rows: ( self collect: [ :a | aVector collect: [ :b | a * b]])]
```

I've made a pull request, but it seems that it contains too many files. Did I do something wrong?

**Comment by SergeStinckwich** [comment]
Sorry Oleks, but we are not using github for PolyMath code at the moment.
You have to commit your code on SmalltalkHub in the inbox repository and then I will move your code after review: http://smalltalkhub.com/#!/~PolyMath

**Comment by olekscode** [comment]
Should I just commit (Save) it to
http://smalltalkhub.com/mc/PolyMath/PolyMathInbox/main, or do I have to
create a Slice?

If I try to commit it, Monticello wants to add about a hundred different
files from the Math-Matrix package (I assume that's because PolyMathInbox
is not up-to-date with PolyMath).

And if I want to create a slice, it asks me for the issue number. I was
looking for PolyMath issues on FogBugz, but I couldn't find them there.

Also, I think I should create a test for this issue. Should I?

On Thu, May 11, 2017 at 10:21 AM, Serge Stinckwich <notifications@github.com

**Comment by SergeStinckwich** [comment]
Yes you have to commit a slice in the inbox :-) Can you give your ID on SmalltalkHub, so I can add you to the PolyMath org on Smalltalk.

For the issue number, use the number here. All PolyMath issues are on this tracker.

Yes this is better to have a test for the issue :-)

**Comment by olekscode** [comment]
OK, I have just submitted that slice. I will write a test and submit it
with the next slice.
My username on Smalltalkhub is Oleks

On Thu, May 11, 2017 at 11:14 AM, Serge Stinckwich <notifications@github.com

**Comment by SergeStinckwich** [comment]
Don't push in Pharo 6 inbox, but PolyMath inbox.
I add you to the PolyMath org.

**Comment by olekscode** [comment]
I choose PolyMathInbox, but when I try to make a slice and enter the issue
number (25) it suggests me the label "7140-CollectionsTests" which is
probably from a different issue, because then my slice goes to Pharo 6
Inbox. Am I doing it wrong?
​

On Thu, May 11, 2017 at 11:29 AM, Serge Stinckwich <notifications@github.com

**Comment by SergeStinckwich** [comment]
I dunno exactly what you have done. Can you discuss the situation on Discord ?

**Comment by SergeStinckwich** [comment]
I can close now ?

**Comment by olekscode** [comment]
@SergeStinckwich , yes
If all tests are passing now (and they should), you can close this issue

**Comment by SergeStinckwich** [comment]
all tests pass now. Thank you Oleks !
