### ISSUE TITLE
Lot of tests failing on #addWithVector:

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#61]
Apparently we have a lot of tests failing on DNU with #addWithVector: because applied on an Array.

@olekscode maybe this is the code you add:  https://github.com/PolyMathOrg/PolyMath/commit/1ea0c2f45b160d3a95e5f32fb11f4595b48da95f ?

**Comment by olekscode** [comment]
I have found on Discord the description of what I did.

@SergeStinckwich you don't have to read the following. I'm putting it here because it's a nice way to document the changes I make.
**Short version:** I reimplemented `+` using double dispatch for `PMVector` and `Number`. But we also need support for `Array`. So I'm moving the method `addWithVector:` from `PMVector` to its superclass `ArrayedCollection`. This fixes all the red tests and allows us to add other collections to `PMVector`.

-------------

There was a red test that was testing the functionality that was not implemented at the moment.
```Smalltalk
testMatrixElementwiseAdd
    | a b |
    a := PMMatrix rows: #(#(1 2) #(3 4)).
    b := PMMatrix rows: #(#(2 3) #(4 5)).
    self assert: a + 0 equals: a.
    self assert: 0 + a equals: a.
    self assert: a + 1 equals: b.
    self assert: 1 + a equals: b.
    self assert: -1 + b equals: a.
    self assert: b + -1 equals: a.
```
Basically, it's testing if we can add scalars to matrices. But `PMMatrix>>+` could only add two matrices. So I rewrote that method adding double dispatch for `PMMatrix` and `Number`. And I did the same for `PMVector`.
```Smalltalk
PMMatrix >> + aMatrixOrNumber
    "Answers the sum of the receiver with aMatrix."
    ^ aMatrixOrNumber addWithRegularMatrix: self
```
```Smalltalk
"old implementation"
PMMatrix >> addWithRegularMatrix: aMatrix
    "Answers the sum of the receiver with aMatrix as a PMMatrix."
    | n |
    n := 0.
    ^ PMMatrix rows: ( self rowsCollect: [ :each | n := n + 1. each + ( aMatrix rowAt: n)])
```
```Smalltalk
PMVector >> + aVectorOrNumber
    "Answers the sum of the receiver with a vector or number."
    ^ aVectorOrNumber addWithVector: self
```
```Smalltalk
"old implementation"
PMVector >> addWithVector: aVector
    "Answers the sum of the receiver with aVector."
    | answer n |
    answer := self class new: self size.
    n := 0.
    self with: aVector do:
        [ :a :b | 
          n := n + 1. 
          answer at: n put: ( a + b).
        ].
    ^answer
```
```Smalltalk
Number >> addWithVector: aVector
    "Adds itself to each element of the vector"
    ^ aVector collect: [ :each | each + self ]
```
```Smalltalk
Number >> addWithRegularMatrix: aMatrix
    "Adds itself to every row of the matrix"
    ^ PMMatrix rows: (aMatrix rowsCollect: [ :row | row + self ])
```

-------------

Apparently, besides from `Number` and another `PMVector`, we want to be able to add `Array` to `PMVector`. I have moved the method `addWithVector:` from `PMVector` to its superclass `ArrayedCollection`. Because it makes sense to allow adding any arrayed collection (`Array`, `ByteArray`, `FloatArray` etc.) to `PMVector`.
