### ISSUE TITLE
Implement argmax on a PMMatrix

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#80]
Implement something similar to this one : https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html on PMMatrix

**Comment by nicolas-cellier-aka-nice** [comment]
The numpy example is quite stupid because ambiguous: we don't know if 5 is the 0-based index of the maximum value, or the maximum value itself!

Also we don't know what happens with negative values... I presume it's the maximum value and  not the maximum magnitude, but it would be good to have an example for disambiguating.

Answering a single index only make sense for an underlying flatten collection like in Smallapack.
But this is not the case of Didier Besset matrix implementation (Array of Array).
Can we access a PMMatrix with a single flat index?
Otherwise we should answer a row and a column index (or alternatively provide a block [:rowIndex :colIndex | ] as argument).

**Comment by nicolas-cellier-aka-nice** [comment]
Note that in Smallapack I've implemented findMax: with a block argument which is (self collect: aBlock) argmax.
I also have findAll: which is equivalent of Matlab find (same as select: but answers the indices rather than the elements).

**Comment by SergeStinckwich** [comment]
Yes the Numpy example is quite stupid ... Apparently without axis, the matrix is flattened before finding the argmax.
