### ISSUE TITLE
2 PCA implementations that give same results but different from Python scikit-learn implementation ...

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#81]
We have 2 implementations of PCA : 
- one based on Jacobi Transformation of the covariance matrix
- another one based on SVD.

They give the same results but the result are different from the one you can find with sci-kit learn in Python: 

```python
import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)
pca.fit(X)
pca.components_
pca.transform(X)
```
``pca.components_`` returns : 

```python
array([[-0.83849224, -0.54491354],
       [ 0.54491354, -0.83849224]])
```

``pca.transform(X)`` returns:

```python
array([[ 1.38340578,  0.2935787 ],
       [ 2.22189802, -0.25133484],
       [ 3.6053038 ,  0.04224385],
       [-1.38340578, -0.2935787 ],
       [-2.22189802,  0.25133484],
       [-3.6053038 , -0.04224385]])
```

I try to implement a flipsvd method like this one : https://github.com/scikit-learn/scikit-learn/blob/4c65d8e615c9331d37cbb6225c5b67c445a5c959/sklearn/utils/extmath.py#L609
but fails until now. 

Please have a look to tests of ``PMPrincipalComponentAnalyserTest``.

**Comment by hemalvarambhia** [comment]
Hi, @SergeStinckwich I looked into the failing test for the Jacobi Transformation form of PCA a little deeper and noted that **transposing and negating the matrix of eigenvectors** results in the test passing (see screenshot):
![transposeandnegate](https://user-images.githubusercontent.com/2665571/51270525-0e3e7b80-19bd-11e9-83a9-126e1614b6c5.png)

The Scikit Learn library, from what I can see, uses the SVD implementation which involves flipping signs. For this test, then, does it make sense to compare the Jacobi implementation directly with their SVD computed one? Should we instead assert that the negated transpose of the Jacobi implementation equals the SVD one?

**Comment by hemalvarambhia** [comment]
Hi, @SergeStinckwich I looked into the failing test for the Jacobi Transformation form of PCA a little deeper and noted that transposing and negating the matrix of eigenvectors results in the test passing:

![transposeandnegate](https://user-images.githubusercontent.com/2665571/51271201-ce789380-19be-11e9-8ea4-d0b09c693668.png)

The Scikit Learn library, from what I can see, uses the SVD implementation which involves flipping signs. For this test, then, does it make sense to directly compare the Jacobi matrix of eigenvectors with their SVD computed one? Might we instead assert that the negated transpose of Jacobi equals the SVD one?

Please forgive my ignorance- I'm not too familiar with this domain.

**Comment by hemalvarambhia** [comment]
I noted a similar thing with PolyMath's PCA implementation using SVD, where transposing and negating the returned matrix from `transformMatrix` gets the test passing:

![pca_svd_test](https://user-images.githubusercontent.com/2665571/51280177-ec51f280-19d6-11e9-8a15-801964175a1a.png)

This phenomenon is interesting, I think. Perhaps worth investigating.

Also I note that `flipEigenvectorsSign` has been commented out in the `fit:` message because it doesn't work.

**Comment by hemalvarambhia** [comment]
Hi, @SergeStinckwich, 
I made some more progress on this, where I extracted out the algorithm from SciKit-Learn and tried to determine the outputs of each step. Here is something you can run on the command line to see this at a more granular level: [scikit-learn flip algorithm](https://gist.github.com/hemalvarambhia/620711e22c9ad01d6d55a0530cc28c18)

Given that in SciKit-Learn, `U` is
```
[[-0.21956688  0.53396977]
 [-0.35264795 -0.45713538]
 [-0.57221483  0.07683439]
 [ 0.21956688 -0.53396977]
 [ 0.35264795  0.45713538]
 [ 0.57221483 -0.07683439]]
```
(the first two columns from PolyMath match SciKit-Learn's)

the first thing to note is the `max_abs_column` variable, which in SciKitLearn is a 2-element array: `[2 0]`, whereas in PolyMath it is `#(3 4 5...)`. For the former, this leads to a sub matrix: `[-0.57221483  0.53396977]`, which then leads to the signs being `[-1 1]`. This is the key difference because in PolyMath, we get `#(-1-1 -1 1 1 -1)`. Our function, our `argMaxOnColumns.` message yields `-0.53396...` from row 4, column 2 rather than 0.53396977 at row 1.

**Comment by hemalvarambhia** [comment]
On further investigation, when we compute the max_aabs_column in PolyMath, we get the row 4 as the element with the high value because it is 0.53396977373779**11** whereas at row 1 it is 0.53396977373779**03**

**Comment by SergeStinckwich** [comment]
In Mathematica if we use SVD: 
```mathematica
m = {{-1, -1}, {2, -1}, {-3, -2}, {1, 1}, {2, 1}, {3, 2}}
{{-1, -1}, {2, -1}, {-3, -2}, {1, 1}, {2, 1}, {3, 2}}
{u, w, v} = SingularValueDecomposition[N[m]]
{{{0.227413, -0.184384, -0.602751, 0.246542, 0.356209, 
   0.602751}, {-0.204296, -0.949274, 0.0746245, 
   0.109693, -0.184317, -0.0746245}, {0.598729, -0.113805, 0.705625, 
   0.128753, 0.165622, 0.294375}, {-0.227413, 0.184384, 0.106997, 
   0.942819, -0.0498161, -0.106997}, {-0.371316, -0.070579, 
   0.187377, -0.0715718, 0.884194, -0.187377}, {-0.598729, 0.113805, 
   0.294375, -0.128753, -0.165622, 0.705625}}, {{6.01037, 0.}, {0., 
   1.96863}, {0., 0.}, {0., 0.}, {0., 0.}, {0., 
   0.}}, {{-0.86491, -0.501927}, {-0.501927, 0.86491}}}
v
{{-0.86491, -0.501927}, {-0.501927, 0.86491}}
```

**Comment by SergeStinckwich** [comment]
Action points : 
- try to find another example as an acceptance tests
- run this example against PolyMath, Mathematica and scikit learn to order to find some patterns
- how SVD is done in Numpy ? what are the decisions taken by them ?

**Comment by hemalvarambhia** [comment]
I tried Wolfram Alpha and for the V matrix, we seem to match:
[Wolfram Alpha](https://www.wolframalpha.com/input/?i=SVD+%7B%7B-1,-1%7D,%7B-2,-1%7D,%7B-3,+-2%7D,+%7B1,+1%7D,+%7B2,+1%7D,+%7B3,+2%7D%7D)

**Comment by SergeStinckwich** [comment]
[Why Mathematica SVD is different from another math engine ](https://mathematica.stackexchange.com/questions/107362/mathematicas-singular-value-decomposition-different-from-another-math-engine)
Mathematica SVD documentation: https://reference.wolfram.com/language/ref/SingularValueDecomposition.html

**Comment by hemalvarambhia** [comment]
Wolfram Alpha:
<img width="774" alt="Screen Shot 2019-03-27 at 17 55 21" src="https://user-images.githubusercontent.com/2665571/55100353-9924ac00-50b9-11e9-8777-3ea0dc87f364.png">

**Comment by hemalvarambhia** [comment]
Polymath calculation: here we see it matches Wolfram Alpha exactly:
![polymath_calculation](https://user-images.githubusercontent.com/2665571/55116322-cafc3980-50de-11e9-89f7-d7f12e75c731.png)

**Comment by hemalvarambhia** [comment]
The next example we could try is in section 3.1 of this [article](http://www.cs.otago.ac.nz/cosc453/student_tutorials/principal_components.pdf)

[Here](https://www.wolframalpha.com/input/?i=SVD+%7B%7B2.5,+2.4%7D,+%7B0.5,+0.7%7D,+%7B2.2,+2.9%7D,+%7B1.9,+2.2%7D,+%7B3.1,+3.0%7D,+%7B2.3,+2.7%7D,+%7B2,+1.6%7D,+%7B1,+1.1%7D,+%7B1.5,+1.6%7D,+%7B1.1,+0.9%7D%7D) is the answer according to Wolfram Alpha.

**Comment by hemalvarambhia** [comment]
In relation to the first of our action points, to find another example to, I tried the example in section 3.1 of the [PCA tutorial](http://www.cs.otago.ac.nz/cosc453/student_tutorials/principal_components.pdf). The PCA of scikit learn matches the output published in the above paper almost exactly:. 

```
[[-0.82797019 -0.17511531]
 [ 1.77758033  0.14285723]
 [-0.99219749  0.38437499]
 [-0.27421042  0.13041721]
 [-1.67580142 -0.20949846]
 [-0.9129491   0.17528244]
 [ 0.09910944 -0.3498247 ]
 [ 1.14457216  0.04641726]
 [ 0.43804614  0.01776463]
 [ 1.22382056 -0.16267529]]
```

This is not the case for PolyMath, sadly, for both implementations. However, as we've discovered, the problem is a bit further up, in how we're computing the eigenvectors.

**Comment by hemalvarambhia** [comment]
@SergeStinckwich Out of curiosity, I used the **mean centred** data from the [PCA tutorial](http://www.cs.otago.ac.nz/cosc453/student_tutorials/principal_components.pdf):

| x  |   y |
| ----| ---- |
| .69      | .49 |
| -1.31  | -1.21 |
| .39 | .99 |
| .09 | .29 |
| 1.29 | 1.09 |
| .49 | .79 |
| .19 | -.31 |
| -.81 | -.81 |
| -.31 | -.31 |
| -.71 | -1.01 |

and PolyMath's output is correct up to negation:

![polymath_pca_tutorial_example](https://user-images.githubusercontent.com/2665571/56444832-58076c80-62f2-11e9-95ad-afa61f4f4669.png)

**Comment by hemalvarambhia** [comment]
On point 3, Scikit-Learn uses scipy for the SVD part of the PCA. In turn scipy delegates to LAPACK driver routines and according to [the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html#scipy.linalg.svd). by default, it uses `gessd`. The available options are `gessd` and `gesvd`. I could not see anything in the scipy source code (`decomp_svd.py`) that indicated the decision taken in flipping signs.
